proj4php/proj4php

README.md
src/Common.php
src/Datum.php
src/LongLat.php
src/Point.php
src/Proj.php
src/Proj4php.php
src/defs/EPSG2154.php
src/projCode/Cass.php
src/projCode/Gstmerc.php
src/projCode/Lcc.php
src/projCode/Sterea.php

#2 #5 closed

---

src/Datum.php
src/Proj.php
src/Proj4php.php
vendor/autoload.php

Set a default autoloader to work without composer.

Adding composer - default autoloader

---

src/Point.php

Debug constructor of point with array, or string in one parameter.
Exemple :
new Point("10 2")   or new Point(array(10, 2))

Debug constructor of point with array, or string in one parameter

---

README.md
src/Proj.php
test/Proj4phpTest.php
test/testproj.php

merge sources from https://github.com/nickolanack/proj4php
add unit test for these two methods : 
$proj4->addDefs
new Proj('PROJCS[...

fix 2 methods for inline projection definitions

---

src/Datum.php
src/Proj.php
src/Proj4php.php
src/projCode/Lcc.php
test/Proj4phpTest.php

Adding new conversions methods.
Fix unit tests for EPSG:31370
Introduce debugging
parse wkt unit test (mostly from @nickolanack)
@nickolanack 
@coreation
@judgej

Inline projections

---

src/Proj4php.php
test/Proj4phpTest.php

added unit test
please make sure that this makes sense - it should address the issue recently reported by @surbinati  
Conversion from EPSG 900913 to EPSG 3003 seems wrong #37

added missing transcode to wgs if not in source or destination

---

src/projCode/Sterea.php

Misssing dollar sign breaks conversion to RD

Missing dollar sign in sterea for some reason

---

src/defs/EPSG27561.php

Will now support "Lambert Nord France" projection

Added file EPSG27561

---

src/defs/EPSG27562.php

Class can now support "Lambert Centre France" projection

Added file

---

src/defs/EPSG27561.php

Fixed a mistake in EPSG27561.php

---

src/defs/EPSG3825.php
src/defs/EPSG3826.php
src/defs/EPSG3827.php
src/defs/EPSG3828.php
test/Proj4phpTest.php

TWD67 = EPSG3827/EPSG3828
TWD97 = EPSG3825/EPSG3826

add TWD67/TWD97 based on parameters from QGIS

---

src/defs/EPSG3112.php
test/CommonTest.php
test/Proj4phpTest.php

- Added EPSG3112/GDA94 
- Added test to Proj4phpTest
- Some format tidying of Proj4phpTest

Added EPSG3112

---

src/projCode/Aeqd.php

lon should read p->x as @rorso tell in #75

---

src/projCode/Gnom.php

g should read $g as @rorso tells in #74

---

src/defs/EPSG32635.php
src/defs/EPSG32636.php
src/defs/EPSG32637.php
src/defs/EPSG32638.php
src/defs/EPSG32639.php
src/defs/EPSG32640.php
src/defs/EPSG32641.php

some updates, I'm interested to use it and develop more.
Let me know if you are interested

 #update1: update EPSG 32635 - 32641

---

src/Proj4php.php

reflects the changes made with https://github.com/proj4php/proj4php/commit/d3c5784d54b64098a4a93ae864d185ea6fb083be

use predefined EPSG-codes correctly

---

src/proj4php/defs/EPSG3857.php

In order to replace inline sources of proj4php into our project (Lizmap), by the composer package of proj4php, we need to have this def into the official package of proj4php.

Add def EPSG3857

---

src/Wkt.php

@julien2512 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/proj4php/proj4php/

Scrutinizer Auto-Fixes

---

src/defs/EPSG3347.php

Added EPSG:3347 (see https://epsg.io/3347)
Working in a GIS project and noticed this had not been included in the defs, so I PR'd it for posterity's sake :)

Added EPSG3347 (StatsCanada WGS 84)

---

src/projCode/Merc.php

Missing $ in Merc #109

---

src/defs/EPSG3812

Add Belgian Lambert 2008 projection

---

src/defs/EPSG3067.php

Add Finnish EPSG:3067 coordinate system

Create EPSG31254.php for ETRS89 / ETRS-TM35FIN (EPSG:3067)

---

src/Wkt.php

add albers

---

src/Proj.php
test/Proj4phpTest.php

fix proj4 bug, not using ft to meter convertions for unit=ft or unit=us-ft
